version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis_chat
    volumes:
      - ./redisdata:/bitnami/redis/data
    ports:
      - 6379:6379
    environment:
      - REDIS_AOF_ENABLED=no
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - chat

  mongodb:
    hostname: mongo_chat
    container_name: mongo_chat
    image: mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - '127.0.0.1:27017:27017'
    networks:
      - chat

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgresdb:
    hostname: postgres_chat
    container_name: postgres_chat
    image: postgres:alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data:rw
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    networks:
      - chat

networks:
  chat:
    driver: bridge

volumes:
  mongodata:
  postgresdata:

